import {StyleSheet} from 'react-native';
import vh from '../../Units/vh';
import vw from '../../Units/vw';
import {
  primaryColor,
  secondaryColor,
  default_font_Color,
  sub_section_primaryColor,
  default_section_Color,
  default_placeholderColor,
  defaultShadowColor,
  defaultActiveSliderButton,
  defaultInActiveSliderButton,
  default_cartLabel_Color
} from '../../../config.json';

export default StyleSheet.create({
  headerContainer: {
    flexDirection: 'row',
    backgroundColor: default_section_Color,
    paddingHorizontal: vw * 3,
    height: vh * 8,
    alignItems: 'flex-end',
    paddingBottom: vh * 1,
    justifyContent: 'space-between',
  },
  headerInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  menu: {width: vw * 8, height: vh * 4},
  searchbar: {
    flexDirection: 'row',
    width: vw * 82,
    paddingHorizontal: vw * 4,
    height: vh * 6,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderColor: '#FFCFE5',
    backgroundColor: default_section_Color,
    shadowColor: defaultShadowColor,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    borderRadius: vh * 3,
    elevation: 5,
  },
  input: {color: default_placeholderColor, fontSize: vh * 2, padding: 0},
  search: {width: vw * 4, height: vh * 5},
  dot: {
    width: vw * 8,
    height: vh * 1,
    borderRadius: vh * 0.8,
    backgroundColor: defaultActiveSliderButton,
    opacity: 1,
  },
  inactiveDot: {
    width: vw * 5,
    height: vh * 1,
    borderRadius: vh * 0.8,
    backgroundColor: defaultInActiveSliderButton,
  },
  banner: {
    width: vw * 92,
    height: vh * 22.2,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  bannerTxt: {
    color: default_section_Color,
    fontSize: vh * 2.7,
    width: '50%',
    marginLeft: vw * 5,
  },
  categories: {
    width: vw * 92,
    backgroundColor: default_section_Color,
    shadowColor: defaultShadowColor,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
    paddingHorizontal: vw * 4,
    paddingTop: vh * 1.5,
    paddingBottom: vh * 2.5,
    alignSelf: 'center',
    borderRadius: vw * 3,
  },
  catHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  categoriesTxt: {color: default_font_Color, fontSize: vh * 2.2},
  viewAll: {color: primaryColor, fontSize: vh * 1.7},
  catRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: vh * 1,
    width: '100%',
    alignSelf: 'center',
    flexWrap: 'wrap',
  },
  cat1: {
    width: '32%',
    backgroundColor: sub_section_primaryColor,
    alignItems: 'center',
    paddingVertical: vh * 0,
    borderRadius: vw * 1,
    height: vh * 17,
    marginBottom: vh * 1,
    paddingHorizontal: vw * 2,
  },
  carImg1: {width: vw * 22, height: vh * 12, marginTop: vh * 0},
  catTxt1: {color: secondaryColor, fontSize: vh * 1.8, marginTop: vh * 1},
  catTxt3: {color: secondaryColor, fontSize: vh * 2.5},
  catRow2: {
    flexDirection: 'row',
    width: '64%',
    backgroundColor: sub_section_primaryColor,
    paddingVertical: vh * 2,
    borderRadius: vw * 1,
    height: vh * 17,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: vh * 1,
    paddingHorizontal: vw * 2,
  },
  catRow3: {
    width: '64%',
    backgroundColor: sub_section_primaryColor,
    paddingVertical: vh * 0,
    borderRadius: vw * 1,
    height: vh * 17,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: vh * 1,
    paddingHorizontal: vw * 2,
  },
  catTxt2: {
    color: '#92278F',
    fontSize: vh * 2.8,
    width: '40%',
    marginLeft: vw * 5,
  },
  catImg2: {width: '55%', height: vh * 16},
});
